Fix an error for `bundle install` when using Ruby 3.2.2
Ruby 3.2.2 を使用していたのですが、`bundle install` に失敗するようでした。
そのため、Gemfile.lockを削除して `bundle install` を実行して再生成しました。

`bundle exec jekyll server` を実行してエラー終了しないことを確認しています。

## ruby version
```
❯ ruby --version
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-darwin21]
```

## Error log
```
❯ bundle install
/ydah/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-1.16.4/lib/bundler/shared_helpers.rb:266:in `search_up': undefined method `untaint' for "/ydah/kansai-ruby-community":String (NoMethodError)

      current  = File.expand_path(SharedHelpers.pwd).untaint
                                                    ^^^^^^^^
        from /ydah/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-1.16.4/lib/bundler/shared_helpers.rb:253:in `find_file'
        from /ydah/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-1.16.4/lib/bundler/shared_helpers.rb:245:in `find_gemfile'
        from /ydah/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-1.16.4/lib/bundler/shared_helpers.rb:27:in `root'
        from /ydah/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-1.16.4/lib/bundler.rb:220:in `root'
        from /ydah/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-1.16.4/lib/bundler.rb:232:in `app_config_path'
        from /ydah/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-1.16.4/lib/bundler.rb:259:in `settings'
        from /ydah/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-1.16.4/lib/bundler/feature_flag.rb:21:in `block in settings_method'
        from /ydah/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-1.16.4/lib/bundler/cli.rb:97:in `<class:CLI>'
        from /ydah/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-1.16.4/lib/bundler/cli.rb:7:in `<module:Bundler>'
        from /ydah/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-1.16.4/lib/bundler/cli.rb:6:in `<top (required)>'
        from <internal:/ydah/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:97:in `require'
        from <internal:/ydah/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:97:in `require'
        from /ydah/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-1.16.4/exe/bundle:23:in `block in <top (required)>'
        from /ydah/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-1.16.4/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
        from /ydah/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-1.16.4/exe/bundle:22:in `<top (required)>'
        from /ydah/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
        from /ydah/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'
```